sudo: required

language: python

python:
  - "3.4"

services:
  - docker

cache:
  - apt
  
env:
  - MONGO_IMAGE=mongo:2.4 ES_IMAGE=elasticsearch:1.6.2 DOCKER_OPTIONS="-e WIDUKIND_MONGODB_NAME=widukind_test -e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test -e WIDUKIND_ES_URL=http://elasticsearch:9200 -e WIDUKIND_ES_INDEX=widukind_test --link=mongodb:mongodb --link=elasticsearch:elasticsearch --rm"
  - MONGO_IMAGE=mongo:2.6 ES_IMAGE=elasticsearch:1.7 DOCKER_OPTIONS="-e SKIP_RELEASE_CONTROL=1 -e WIDUKIND_MONGODB_NAME=widukind_test -e WIDUKIND_MONGODB_NAME=widukind_test -e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test -e WIDUKIND_ES_URL=http://elasticsearch:9200 -e WIDUKIND_ES_INDEX=widukind_test --link=mongodb:mongodb --link=elasticsearch:elasticsearch --rm"
  - MONGO_IMAGE=mongo:3.0 ES_IMAGE=elasticsearch:1.7 DOCKER_OPTIONS="-e SKIP_RELEASE_CONTROL=1 -e WIDUKIND_MONGODB_NAME=widukind_test -e WIDUKIND_MONGODB_NAME=widukind_test -e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test -e WIDUKIND_ES_URL=http://elasticsearch:9200 -e WIDUKIND_ES_INDEX=widukind_test --link=mongodb:mongodb --link=elasticsearch:elasticsearch --rm"
  #- MONGO_IMAGE=mongo:3.0 ES_IMAGE=elasticsearch:2 DOCKER_OPTIONS="-e SKIP_RELEASE_CONTROL=1 -e WIDUKIND_MONGODB_NAME=widukind_test -e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test -e WIDUKIND_ES_URL=http://elasticsearch:9200 -e WIDUKIND_ES_INDEX=widukind_test --link=mongodb:mongodb --link=elasticsearch:elasticsearch --rm"
  #- MONGO_IMAGE=mongo:3.1 ES_IMAGE=elasticsearch:1.6.2 DOCKER_OPTIONS="-e SKIP_RELEASE_CONTROL=1 -e WIDUKIND_MONGODB_NAME=widukind_test -e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test -e WIDUKIND_ES_URL=http://elasticsearch:9200 -e WIDUKIND_ES_INDEX=widukind_test --link=mongodb:mongodb --link=elasticsearch:elasticsearch --rm"

before_install:
  - docker pull $MONGO_IMAGE
  - docker pull $ES_IMAGE
  - docker run -d --name=mongodb $MONGO_IMAGE mongod --smallfiles --noauth --directoryperdb 
  - docker run -d --name=elasticsearch $ES_IMAGE
  #- "if [[ $ES_IMAGE == 'elasticsearch:2' ]]; then sed -i 's/^elasticsearch.*/elasticsearch/' requirements.txt setup.py; fi"
  - docker build -t widukind/dlstats .
 
-install:
  - pip install coveralls
 
before_script:
  - sleep 15
  - env
  - docker run $DOCKER_OPTIONS widukind/dlstats pip freeze

script:
  - docker run $DOCKER_OPTIONS widukind/dlstats dlstats --version
  - docker run $DOCKER_OPTIONS widukind/dlstats dlstats es check
  - docker run $DOCKER_OPTIONS widukind/dlstats dlstats mongo check
  - docker run $DOCKER_OPTIONS -v $PWD/coverage:/code/coverage widukind/dlstats nosetests --with-coverage -s -v dlstats
  - docker run $DOCKER_OPTIONS widukind/dlstats flake8 --exit-zero dlstats
  
after_script: coveralls --verbose

notifications:
  email: true
  on_success: always
  on_failure: always
