sudo: required
language: python

python:
    - "3.4"

install:                                                                                                                                                                                                                            
    - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install mongodb
    - pip install requests
    - pip install pymongo
    - pip install pandas
    - pip install docopt
    - pip install voluptuous
    - pip install xlrd
    - pip install elasticsearch
    - pip install configobj
    - cp config/dlstats ~/.dlstats

before_script:
    - cp /etc/mongodb.conf ~/.mongoconf
    - echo "replSet=rs0" | sudo tee -a ~/.mongoconf
    - echo "port=27017" | sudo tee -a ~/.mongoconf
    - echo "fork = true" | sudo tee -a ~/.mongoconf
    - echo "dbpath = /data/db" | sudo tee -a ~/.mongoconf
    - echo "logpath = /data/log/mongod.log" | sudo tee -a ~/.mongoconf
    - echo "logappend = true" | sudo tee -a ~/.mongoconf
    - echo "journal = true" | sudo tee -a ~/.mongoconf
    - echo "quiet = true" | sudo tee -a ~/.mongoconf
    - sudo mkdir -p /data/db /data/log
    - sudo cat /home/travis/.mongoconf
    - sudo mongod --config ~/.mongoconf
    - sleep 10
     - |
       echo "Testing MongoDB connection...";tries=4;
       i=0;
       while [ $i -lt $tries ]; do fail=$(mongo --eval db 2>&1 >/dev/null | grep "connect failed");
         if [ "$fail" ] && [ $[ $i+1 ] -eq $tries ] ; then echo "Error: Could not connect to mongodb"; exit 1;
         elif [ "$fail" ]; then echo "Connection failed. Retrying"; sleep 3; i=$[ $i+1 ];
         else echo "OK"; i=$tries; fi;
       done
    - echo "... MongoDB OK"
    - sudo mongo --port 27017 --host '127.0.0.1' --eval 'rs.initiate()'
      
script: nosetests
