sudo: required
language: python
services:
      - mongodb

python:
    - "3.4"

install:                                                                                                                                                                                                                            
    - pip install requests
    - pip install pymongo
    - pip install pandas
    - pip install docopt
    - pip install voluptuous
    - pip install xlrd
    - pip install elasticsearch
    - pip install configobj
    - cp config/dlstats ~/.dlstats

before_script:
    - echo "replSet = rs0" | sudo tee -a /etc/mongodb.conf
    - sudo service mongodb restart
    - sleep 20
    - mongo --eval 'rs.initiate()'
    - sleep 15
      
script: nosetests
